[book]
authors = ["jjui contributors"]
language = "en"
src = "."
title = "jjui"

[output.html]
git-repository-url = "https://github.com/idursun/jjui"
edit-url-template = "./wiki_edit/{path}"
additional-js = ["./theme/md_links.js"]
additional-css = ["./theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
